virtuoso:
  restart: always
  image: tenforce/virtuoso:1.1.0-virtuoso7.2.4
  environment:
    DBA_PASSWORD: dba
    SPARQL_UPDATE: "true"
  volumes:
    - ./data/virtuoso:/data
    - ./scripts:/scripts
    - /usr/local/virtuoso-opensource/lib
    - ../backup:/backup
    - ../import-data:/import-data

php-ontowiki:
  restart: always
  image: aksw/php-5.6-fpm-odbc-virtuoso
  volumes_from:
    - virtuoso
  links:
    - virtuoso
  volumes:
    - ./data/php-ontowiki:/var/www/
    - ../backup:/backup
    - ../import-data:/import-data

nginx-ontowiki:
  restart: always
  image: nginx
  links:
    - php-ontowiki
  ports:
    - 8580:80
  mem_limit: 512MB
  volumes_from:
    - php-ontowiki
  volumes:
    - ./data/nginx-ontowiki/ssl/:/etc/nginx/ssl/:rw
    - ./data/nginx-ontowiki/conf.d/:/etc/nginx/conf.d/:rw
    - ./data/nginx-ontowiki/log/:/var/log/nginx/:rw

php-cpm:
  restart: always
  image: php:7-fpm
  volumes:
    - ./data/php-cpm:/var/www/
    - ../backup:/backup

nginx-cpm:
  restart: always
  image: nginx
  ports:
    - 8581:80
  mem_limit: 512MB
  volumes_from:
    - php-cpm
  volumes:
    - ./data/nginx-cpm/ssl/:/etc/nginx/ssl/:rw
    - ./data/nginx-cpm/conf.d/:/etc/nginx/conf.d/:rw
    - ./data/nginx-cpm/log/:/var/log/nginx/:rw
  links:
    - php-cpm


nginx-download:
  restart: always
  image: nginx
  ports:
    - 8582:80
  mem_limit: 512MB
  volumes:
    - ./data/nginx-download/ssl/:/etc/nginx/ssl/:rw
    - ./data/nginx-download/conf.d/:/etc/nginx/conf.d/:rw
    - ./data/nginx-download/log/:/var/log/nginx/:rw
    - ./data/nginx-download/www/:/var/www/

nginx-proxy:
  restart: always
  image: nginx
  ports:
    - 80:80
#    - 443:443
  restart: always
  mem_limit: 512MB
  volumes:
    - ./data/nginx-proxy/ssl/:/etc/nginx/ssl/:rw
    - ./data/nginx-proxy/conf.d/:/etc/nginx/conf.d/:rw
    - ./data/nginx-proxy/log/:/var/log/nginx/:rw

  links:
    - nginx-cpm
    - nginx-ontowiki
    - nginx-download
